CREATE DATABASE IF NOT EXISTS qtella_api;

USE qtella_api;

CREATE TABLE IF NOT EXISTS users (
    id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(200) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    date_of_birth DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
